#cloud-config

package_update: true
package_upgrade: false
package_reboot_if_required: false

groups:
  - docker

users:
  - default
  - name: ethereum
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ${barbosa_ssh_key}
      - ${blackbeard_ssh_key}
      - ${ljs_ssh_key}
    groups:
      - sudo
      - docker
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - unattended-upgrades
  - ssmtp
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - ntp

runcmd:
  - echo "===== Starting droplet initialization ====="
  - echo "===== Installing docker ====="
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io
  - echo "===== Mounting block storage volume ====="
  - mkfs.ext4 /dev/disk/by-id/scsi-0DO_Volume_${eth2_mount_name}
  - mkfs.ext4 /dev/disk/by-id/scsi-0DO_Volume_${eth1_mount_name}
  - mkdir -p /mnt/${eth2_mount_name}
  - mkdir -p /mnt/${eth1_mount_name}
  - mount -o discard,defaults,noatime /dev/disk/by-id/scsi-0DO_Volume_${eth2_mount_name} /mnt/${eth2_mount_name}
  - mount -o discard,defaults,noatime /dev/disk/by-id/scsi-0DO_Volume_${eth1_mount_name} /mnt/${eth1_mount_name}
  - echo '/dev/disk/by-id/scsi-0DO_Volume_${eth2_mount_name} /mnt/${eth2_mount_name} ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
  - echo '/dev/disk/by-id/scsi-0DO_Volume_${eth1_mount_name} /mnt/${eth1_mount_name} ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
  - chown ethereum:ethereum /mnt/${eth2_mount_name}
  - chown ethereum:ethereum /mnt/${eth1_mount_name}
  - echo "===== Finished droplet initialization ====="

# vi: ft=yaml
