#cloud-config

package_update: true
package_upgrade: false
package_reboot_if_required: false

users:
  - default

packages:
  - unattended-upgrades
  - ssmtp
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - echo "===== Starting droplet initialization ====="
  - echo "===== Configuring unattended upgrades ====="
  - sed '/-updates\|-backports\|Remove-/s#^//##; /Remove-/s#false#true#; /\/\//d; /^$/d; /Black/,/};/d' "/etc/apt/apt.conf.d/50unattended-upgrades" | tee "/etc/apt/apt.conf.d/51unattended-upgrades_on"
  - cat "/etc/apt/apt.conf.d/10periodic" "/etc/apt/apt.conf.d/20auto-upgrades" 2>/dev/null | sed "s/0/1/" | sort -u | tee  "/etc/apt/apt.conf.d/21periodic-auto-upgrades_on"
  - timedatectl set-ntp on
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - echo "===== Mounting block storage volume ====="
  - mkfs.ext4 /dev/disk/by-id/scsi-0DO_Volume_${beaconchain_volume_name}
  - mkdir -p /mnt/beaconchain
  - mount -o discard,defaults,noatime /dev/disk/by-id/scsi-0DO_Volume_${beaconchain_volume_name} /mnt/beaconchain
  - echo '/dev/disk/by-id/scsi-0DO_Volume_${beaconchain_volume_name} /mnt/beaconchain ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
  - echo "===== Finished droplet initialization ====="

# vi: ft=yaml
