services:
  geth:
    image: ethereum/go-client
    command: [ '--http', '--http-addr 0.0.0.0', '--goerli' ]
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - ethereum:/root
  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    command: [ '--datadir=/data', '--rpc-host=0.0.0.0', '--monitoring-host=0.0.0.0', '--http-web3provider=geth:8545' ]
    ports:
      - 12000:12000/udp
      - 13000:13000
    volumes:
      - ethereum:/root
  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    command: [ '--beacon-rpc-provider=beacon:4000', '--wallet-dir=/wallet', '--datadir=/validatordb' ]
    ports:
      - 12000:12000/udp
      - 13000:13000
    volumes:
      - etherum:/root

volumes:
  ethereum:
    # The name is enough to define the volume.
