version: 3.4

services:
  geth:
    restart: unless-stopped
    build:
      context: ./geth
      args:
        - TAG=stable
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - web3,eth,net
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.api
      - web3,eth,api
      - --syncmode light
      - --pcscdpath ""
      - --datadir /var/lib/geth
      - --
    stop_signal: SIGINT
    stop_grace_period: 3m
    image: geth:local
    volumes:
      - geth:/var/lib/geth
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
    expose:
      - 8545:8545/tcp  # HTTP RPC port
      - 8546:8546/tcp  # WS RPC port
    networks:
      default:
        aliases:
          - eth1
  eth:
    depends_on:
      - geth

volumes:
  geth:

